// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "forestMonkeyWalkLeft1":
            case "anim3":return [img`
. . . . f f f f f . . . . . . . 
. . . f f f f f f f . . . . . . 
. . f d d d d f f f f . . . . . 
. f d f d d f d f f f f . . . . 
. f d f d d f d f f d d f . . . 
f d d d d d d d f f b d c . . . 
f d d d d c d d 5 5 b d c . f f 
f c c c c d d d 5 5 f c . f 5 f 
. f d d d d d 5 5 f f . . f 5 f 
. . f f f f f 5 5 5 5 f . f 5 f 
. . . . f 5 5 5 5 5 5 5 f f 5 f 
. . . f 5 f f 5 f 5 5 5 5 f f . 
. . . f 5 f f 5 f 5 5 5 5 f . . 
. . . f d b f d b f f 5 f . . . 
. . . f d d c d d b b d f . . . 
. . . . f f f f f f f f f . . . 
`];
            case "forestMonkeyWalkLeft":
            case "anim1":return [img`
. . . . f f f f f . . . . . . . 
. . . f f f f f f f . . . . . . 
. . f d d d d f f f f . . . . . 
. f d f d d f d f f f f . . . . 
. f d f d d f d f f d d f . . . 
f d d d d d d d f f b d c . . . 
f d d d d c d d 5 5 b d c . f f 
f c c c c d d d 5 5 f c . f 5 f 
. f d d d d d 5 5 f f . . f 5 f 
. . f f f f f 5 5 5 5 f . f 5 f 
. . . . f 5 5 5 5 5 5 5 f f 5 f 
. . . f 5 f f 5 f 5 5 5 5 f f . 
. . . f 5 f f 5 f 5 5 5 5 f . . 
. . . f d b f d b f f 5 f . . . 
. . . f d d c d d b b d f . . . 
. . . . f f f f f f f f f . . . 
`, img`
. . . . f f f f f . . . . . . . 
. . . f f f f f f f . . . . . . 
. . f d d d d f f f f . . . . . 
. f d f d d f d f f f . . . . . 
. f d f d d f d f f f f . . . . 
f d d d d d d d f f d d f . . . 
f d d d d c d d f f b d c . . . 
f c c c c d d 5 5 5 b d c . f f 
. f d d d d 5 5 5 f f c . f 5 f 
. f f f f f f 5 5 5 5 f . f 5 f 
. f f f f 5 5 5 5 5 5 5 f f 5 f 
f d d f d d f 5 f 5 5 5 5 f f . 
f d b f d b f 5 f 5 5 5 5 f . . 
f f f f f f f f f f f f 5 f . . 
. . . . . . . . . f c d d f . . 
. . . . . . . . . . f f f f . . 
`, img`
. . . . f f f f f . . . . . . . 
. . . f f f f f f f . . . . . . 
. . f d d d d f f f f f . . . . 
. f d d d d d d f f d d f . . . 
. f d f d d f d f f b d c . . . 
f d d f d d f d 5 5 b d c . f f 
f d d d d d d d 5 5 f c . f 5 f 
f d d d d c d 5 5 5 f . . f 5 f 
. f c c c d 5 5 5 f f . . f 5 f 
. . f f f f f 5 5 5 5 f . f 5 f 
. . . . f 5 5 5 5 5 5 5 f f f . 
. . f f 5 f 5 5 f 5 5 5 5 f . . 
. f 5 f f 5 5 f f f 5 5 5 f . . 
f d d b d d c f f f f f f b f . 
f d d c d d d f . . f c d d f . 
. f f f f f f f . . . f f f . . 
`, img`
. . . . f f f f f . . . . . . . 
. . . f f f f f f f f f . . . . 
. . f d d d f f f f d d f . . . 
. f d d d d d f f f b d c . . . 
. f d d d d d d 5 5 b d c . . . 
f d d f d d f d 5 5 f c . f f . 
f d d f d d f d 5 5 f . . f 5 f 
f d d d d d d d 5 5 f . . f 5 f 
. f d d d c d 5 5 f f . . f 5 f 
. . f f f d 5 5 5 5 5 f . f 5 f 
. . . . f 5 5 5 5 5 5 5 f f f . 
. . . . f f 5 5 5 5 5 b f f . . 
. . . f 5 f f 5 5 c d d f f . . 
. . f d d b d d c f f f . . . . 
. . f d d c d d d f f . . . . . 
. . . f f f f f f f . . . . . . 
`, img`
. . . . f f f f f . . . . . . . 
. . . f f f f f f f . . . . . . 
. . f d d d d f f f f . . . . . 
. f d f d d f d f f f f . . . . 
. f d f d d f d f f d d f . . . 
f d d d d d d d f f b d c . . . 
f d d d d c d d 5 5 b d c . . . 
f c c c c d d 5 5 5 f c . . . . 
. f d d d d 5 5 5 f f . . . . . 
. . f f f f f 5 5 5 5 f . . . . 
. . . . f f 5 5 5 5 5 5 f . f f 
. . . f 5 5 f 5 5 f 5 5 f . 5 f 
. . f 5 5 f 5 5 f 5 5 5 f . 5 f 
. f b d f d b f b b f 5 f f 5 f 
. f d d f d d f d d b 5 f f f f 
. . f f f f f f f f f f f f f . 
`];
            case "forestMonkeyWalkLeft0":
            case "anim2":return [img`
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . f f f f d d d d f . . 
. . . . f f f f d f d d f d f . 
. . . f d d f f d f d d f d f . 
. . . c d b f f d d d d d d d f 
f f . c d b 5 5 d d c d d d d f 
f 5 f . c f 5 5 d d d c c c c f 
f 5 f . . f f 5 5 d d d d d f . 
f 5 f . f 5 5 5 5 f f f f f . . 
f 5 f f 5 5 5 5 5 5 5 f . . . . 
. f f 5 5 5 5 f 5 f f 5 f . . . 
. . f 5 5 5 5 f 5 f f 5 f . . . 
. . . f 5 f f b d f b d f . . . 
. . . f d b b d d c d d f . . . 
. . . f f f f f f f f f . . . . 
`, img`
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . f f f f d d d d f . . 
. . . . . f f f d f d d f d f . 
. . . . f f f f d f d d f d f . 
. . . f d d f f d d d d d d d f 
. . . c d b f f d d c d d d d f 
f f . c d b 5 5 5 d d c c c c f 
f 5 f . c f f 5 5 5 d d d d f . 
f 5 f . f 5 5 5 5 f f f f f f . 
f 5 f f 5 5 5 5 5 5 5 f f f f . 
. f f 5 5 5 5 f 5 f d d f d d f 
. . f 5 5 5 5 f 5 f b d f b d f 
. . f 5 f f f f f f f f f f f f 
. . f d d c f . . . . . . . . . 
. . f f f f . . . . . . . . . . 
`, img`
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . f f f f f d d d d f . . 
. . . f d d f f d d d d d d f . 
. . . c d b f f d f d d f d f . 
f f . c d b 5 5 d f d d f d d f 
f 5 f . c f 5 5 d d d d d d d f 
f 5 f . . f 5 5 5 d c d d d d f 
f 5 f . . f f 5 5 5 d c c c f . 
f 5 f . f 5 5 5 5 f f f f f . . 
. f f f 5 5 5 5 5 5 5 f . . . . 
. . f 5 5 5 5 f 5 5 f 5 f f . . 
. . f 5 5 5 f f f 5 5 f f 5 f . 
. f b f f f f f f c d d b d d f 
. f d d c f . . f d d d c d d f 
. . f f f . . . f f f f f f f . 
`, img`
. . . . . . . f f f f f . . . . 
. . . . f f f f f f f f f . . . 
. . . f d d f f f f d d d f . . 
. . . c d b f f f d d d d d f . 
. . . c d b 5 5 d d d d d d f . 
. f f . c f 5 5 d f d d f d d f 
f 5 f . . f 5 5 d f d d f d d f 
f 5 f . . f 5 5 d d d d d d d f 
f 5 f . . f f 5 5 d c d d d f . 
f 5 f . f 5 5 5 5 5 d f f f . . 
. f f f 5 5 5 5 5 5 5 f . . . . 
. . f f b 5 5 5 5 5 f f . . . . 
. . f f d d c 5 5 f f 5 f . . . 
. . . . f f f c d d b d d f . . 
. . . . . f f d d d c d d f . . 
. . . . . . f f f f f f f . . . 
`, img`
. . . . . . . f f f f f . . . . 
. . . . . . f f f f f f f . . . 
. . . . . f f f f d d d d f . . 
. . . . f f f f d f d d f d f . 
. . . f d d f f d f d d f d f . 
. . . c d b f f d d d d d d d f 
. . . c d b 5 5 d d c d d d d f 
. . . . c f 5 5 5 d d c c c c f 
. . . . . f f 5 5 5 d d d d f . 
. . . . f 5 5 5 5 f f f f f . . 
f f . f 5 5 5 5 5 5 f f . . . . 
f 5 . f 5 5 f 5 5 f 5 5 f . . . 
f 5 . f 5 5 5 f 5 5 f 5 5 f . . 
f 5 f f 5 f b b f b d f d b f . 
f f f f 5 b d d f d d f d d f . 
. f f f f f f f f f f f f f . . 
`];
            case "kaijuMomWalkLeft":
            case "anim4":return [img`
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`];
            case "skellyAttackFront":
            case "anim5":return [img`
........................
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.....fffc1111111f.......
...fc111cd1111111f......
...f1b1b1b1111dddf......
...fbfbffcf11fcddf......
......fcf111111bbf......
.......ccbdb1b1fcf......
.......fffbfbfdff.......
........ffffffff........
........fffffffffff.....
.........fffffc111cf....
.........fffff1b1b1f....
..........ffffbfbfbf....
...........ffff.........
........................
........................
........................
`, img`
........................
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
....5.fd11111111df......
...5..fd11111111df......
...5..fd11111111df......
...4..fddd1111dddff.....
...44.fbdbfddfbdbfcf....
...422fcdcf11fcdcfbf....
....22fffbdb1bdffcf.....
....fcb1bcffffff........
....f1c1c1ffffff........
....fdfdfdfffff.........
.....f.f.f..............
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd111111111f......
......fd11111111df......
......fd11111111df......
......fcdd1111ddcff.....
.......fbcf11fcbfbbf....
.......ffbdb1bdffff.....
........fcbfbfdf........
........ffffffff........
......ffffffffff........
.....fcb1bcffff.........
......ffbff.............
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fdd111111ddf......
......fbdd1111dddf......
......fcdbfddfbdbf......
.......fbcf11fcbfff.....
.......ffb1111bcfbcf....
........fcdb1bdfbbbf....
.......ffffffffffcf.....
.....fcb1bcfffff........
.....f1b1b1ffff.........
......ffbff.............
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f1111111cfff.....
......f1111111dc111cf...
......fddd1111b1b1b1f...
......fddcf11fcffbfbf...
......fbb111111fcf......
......fcf1b1bdbcc.......
.......ffdfbfbfff.......
........ffffffff........
.....fffffffffff........
....fc111cfffff.........
....f1b1b1fffff.........
....fbfbfbffff..........
.........ffff...........
........................
........................
........................
`, img`
........................
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df.5....
......fd11111111df..5...
......fd11111111df..5...
.....ffddd1111dddf..4...
....fcfbdbfddfbdbf.44...
....fbfcdcf11fcdcf224...
.....fcffdb1bdbfff22....
........ffffffcb1bcf....
........ffffff1c1c1f....
.........fffffdfdfdf....
..............f.f.f.....
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......f111111111df......
......fd11111111df......
......fd11111111df......
.....ffcdd1111ddcf......
....fbbfbcf11fcbf.......
.....ffffdb1bdbff.......
........fdfbfbcf........
........ffffffff........
........ffffffffff......
.........ffffcb1bcf.....
.............ffbff......
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fdd111111ddf......
......fddd1111ddbf......
......fbdbfddfbdcf......
.....fffbcf11fcbf.......
....fcbfcb1111bff.......
....fbbbfdb1bdcf........
.....fcffffffffff.......
........fffffcb1bcf.....
.........ffff1b1b1f.....
.............ffbff......
........................
........................
........................
........................
........................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "song1":
            case "mySong":return hex`0078000408020105001c000f0a006400f4010a0000040000000000000000000000000000000002300000000400012504000c0001250c001000012710001800012a18001c0001251c002400012524002800012728003000012a`;
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
